### ISSUE TITLE
Widget rename or icon change overwrites Preprocess icon from Orange3.Data

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#102]
Not sure if this happened in #98 or with the new icons:

![image](https://user-images.githubusercontent.com/19228847/32382675-7c352306-c07b-11e7-8e2a-ebbaf7f5c5af.png)

**Comment by markotoplak** [comment]
This seems like a fun one. :D Thanks!

**Comment by markotoplak** [comment]
Hmmm, it does not happen on either of my Linux, Mac or Windows install... How is Orange and Orange Infrared installed on that machine?

**Comment by markotoplak** [comment]
Can not reproduce. Please reopen if it happens again.
