### ISSUE TITLE
What to do with visible images

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#118]
Has anyone done much thinking about this? A common request is to overlay the visible image with the infrared/other image but this requires at least:

  1. Some standard way of attaching the visible image to the Table/group of spectra
  2. GUI overlay, probably in HyperSpectra

This came up in #117

**Comment by markotoplak** [comment]
Currently orange image widgets handle images as filenames in data tables. This has to be extended somehow  - we shouldn't have make a bunch of temporary files when we open some spectral file.

**Comment by stuart-cls** [comment]
@AlexHenderson Thanks for these notes. I found that ResPro provides a smaller cutout image (at least for mosaic tiles) that covers the same extent as the infrared. There are some minor details but it's better than nothing! I think the microscope becoming misaligned is probably true of any visible/infrared microscope overlay.
