### ISSUE TITLE
Colouring uncustomizable and inconsistent

### ISSUE THREAD

**Issue by tienne-B** [Quasars/orange-spectroscopy#120]
The order of the colours used in graphs are inconsistent between users, making collaborative images coloured inconsistently. While not grave, not being able to change the colours manually compounds the problem. An easy way to verify this bug is to create graphs with two colours with many different computers.

**Comment by markotoplak** [comment]
Thank you. Which graphs do you mean?

**Comment by tienne-B** [comment]
Under the "spectra"-type graphs. Here are two examples from the same dataset (but graphing different things) with the colouring based on the same column (either 0 or 1).
![ab barkx](https://user-images.githubusercontent.com/6293465/34018454-819623a6-e0ef-11e7-95d0-f9d0c1e76408.png)
![wb xylem atr spectro cropped](https://user-images.githubusercontent.com/6293465/34018455-849aaa86-e0ef-11e7-8979-c462a80cf2a4.png)
Even though the selection of data is different, it still shows the colouring problem.

**Comment by markotoplak** [comment]
Thank you for this report. I tried to observe this bug in Spectra widget and was not able to replicate it.

In some cases the same class names can get assigned different colors in different Orange instances. This order depends on the files that have been opened on and the order in which they have been opened.

You can select the colors for the specific classes in the "Color" widget (form the "Data" pane).

**Comment by markotoplak** [comment]
This info should be included in some tutorial.

**Comment by markotoplak** [comment]
After removal of Variable.make in Orange the same files should always load with the same value order and that should not influence the coloring. Plus, now there is a color legend that shows what is being drawn and it is therefore less confusing
