### ISSUE TITLE
Widget the can open multiple files

### ISSUE THREAD

**Issue by markotoplak** [Quasars/orange-spectroscopy#16]
Develop a widget that can open multiple files. This is needed for OPUS.

**Comment by markotoplak** [comment]
I added a basic functionality multifile widget.

Working:
- can open multiple files using machinery from Concatenate
- if schema is saved in folder with files, then the whole folder can be moved and reopened, the same as with ordinary File widget

Missing: 
- easier editing of open filelist (ordering, deleting multiple elements)
- error reporting (reporting missing or unreadable files)

This widget does not handle incompatible spectra. I propose another widget for this.

**Comment by stuart-cls** [comment]
Hi Marko,

I finally had a chance to do some analysis work with this widget, it seems to work very well so far!

I agree that any handling of incompatible spectra should be handled separately and explicitly so we don't surprise our user by interpolating data silently.

**Comment by borondics** [comment]
Multifile has been working well. GUI improvements could be considered, but not so pressing.
