### ISSUE TITLE
Hyperspectra: include ROI group on Selection output when multiple groups

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#168]
In the specific case of multiple ROI groups, it would be nice to include the assignment of those groups in the `Selection` output.

This is already done for the `Data` output, but if the user has a large image and only wants to look at the spectra in a few small regions, they have to manually remove the "Unselected" instances using **Select Rows**.

For single ROI group case, nothing needs to change.

**Comment by markotoplak** [comment]
Fixed in #561
