### ISSUE TITLE
[WINDOWS] lint and coverage setup.py subcommands silently fail when bash is not available

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#188]
It would be nice to have a hint :)

    > python setup.py lint
    running lint
    
    > python setup.py coverage
    running coverage

Actually, after installing pylint I still get crickets. I don't know what to install for the coverage command.

As well as a hint from the command, let's add these to README or CONTRIBUTING

**Comment by stuart-cls** [comment]
A bit of follow-up:

On Windows, the check_pylint_diff script (which is a bash script) silently fails even if you installed pylint (because Windows cmd.exe has no bash). For various annoying reasons I haven't been able to get the git bash shell to activate my conda environment.

So no solution yet.

**Comment by markotoplak** [comment]
I agree, we need some kind of tutorial for contributors.

I asked the only other person I know who develops for Orange on Windows, and he said he can not run `python setup.py lint` locally. I stole lint scripts from Orange.

**Comment by markotoplak** [comment]
We wrote the basic contributing guide. I am closing this because these scripts are not critical.
