### ISSUE TITLE
Too many axes labels on exported graph from Spectra widget

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#213]
**Actual look**
The labels and ticks appear on the top and right axes as well.
![tagish](https://user-images.githubusercontent.com/6304794/45148626-ff062080-b1c7-11e8-9fe9-f4a56a7376e5.png)

**Expected look**
Could we display labels and ticks only on the left and bottom axes?
![image](https://user-images.githubusercontent.com/6304794/45148758-4ab8ca00-b1c8-11e8-96da-d0fd640c0513.png)

**Comment by stuart-cls** [comment]
What do you think about keeping the ticks? I find it helps the eye on the far side of the graph.

**Comment by markotoplak** [comment]
Fixed in #221
