### ISSUE TITLE
List of contributors

### ISSUE THREAD

**Issue by markotoplak** [Quasars/orange-spectroscopy#217]
We need a list of contributors in the repository. For example, a big open source project, GIMP, has a list like this: https://github.com/GNOME/gimp/blob/master/AUTHORS

For this project we could also add a list of institutions that financed the project (there is no such thing on the GIMP list, but here this could be appropriate).

Individual contributors to the code can be mentioned with their just their name or name (institution in parentheses).

What do you think? @borondics @stuart-cls @GioB81 @achimkohler

**Comment by stuart-cls** [comment]
This is a good idea!

I think we should include institutions next to authors names. At least in my case, the CLS contributes via my work time.

@scott-cls ?

**Comment by scott-cls** [comment]
For us (CLS), it is important that we recognize our institution.  I don't think it has to be anything more than in parentheses.  If we had to list all the funding agencies involved, it would be a large list.

**Comment by borondics** [comment]
Of course!!! We will pay attention to acknowledge everyone's contributions
and CLS is on of the top contributiors!

**Comment by borondics** [comment]
How about this one @markotoplak?

**Comment by markotoplak** [comment]
I think this is solved by the quasar web page and the list that github provides.
