### ISSUE TITLE
Handle incompatible spectra

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#23]
### Problem:

User has a set of data, most of which were collected using the same experiment settings, but some were collected with a different spectral window (different detector, for example). They would like to compare these spectra in Orange.
### OPUS solution:

`Make Compatible` function: uses quadratic interpolation to adjust x-scale of spectrum:
- Target spectrum: 1000-5000 cm<sup>-1</sup>, N=4001, dv = 1 cm<sup>-1</sup>
- Spectrum to change: 4000.5-200.5 cm<sup>-1</sup>, N=1901, dv = 2 cm<sup>-1</sup>
- Changed spectrum: 1000-4000 cm<sup>-1</sup>, N=3001, dv = 1 cm<sup>-1</sup>
### Possible implementation

This basically requires the Concatenate widget with interpolation powers and the ability to recognize spectral ranges. I propose re-using most of the Concatenate machinery and adding in an interpolation step.

I'd like some comments or alternative approaches before I embark on this.
Thoughts? @markotoplak @scott-cls @borondics

**Comment by stuart-cls** [comment]
It occurs to me that at least the ability to recognize incompatible spectra will be important for #16

**Comment by stuart-cls** [comment]
This has come up again as I am working on the spectral calculator again. I was hoping the new interpolate widget would handle this case but I think it doesn't:

1. Calculate absorbance from sample/reference single channel energy curves (`Absorbance(ref=RSC_data)(SSC_data)`
2. Load an absorbance file separately
3. Try to concatenate them, either directly or using the interpolate widget on the data from `1.` and the Abs data from `2.` as "points"

You can also see this behavior with a single dataset:
![image](https://cloud.githubusercontent.com/assets/19228847/23726766/1c75c514-041b-11e7-9fd8-6a53167794cf.png)

**Comment by stuart-cls** [comment]
@markotoplak Do you have any ideas on this? I need this behaviour for both of the above cases but I can't quite figure out why they don't concatenate cleanly. Even if you could point me in the right direction I can try to tackle it.

**Comment by markotoplak** [comment]
See the image. But in the meanwhile (in the last month) I fixed interpolation to handle unknowns better so that might have been why it did not work for you for the last time.

![interpolate](https://cloud.githubusercontent.com/assets/552182/25523219/23b38b00-2c06-11e7-980c-29ebe4e0ecf3.png)

**Comment by borondics** [comment]
As a side comment to the picture above... wouldn't it be nice to have a schema repository where we can share them easily? Maybe combined with a widget that handles authentication and downloads...

**Comment by stuart-cls** [comment]
Okay, I see I was using it wrong. But consider: I have two datasets, each with 1660 points but with frequency values different by basically a rounding error. Or not different at all, just the variables aren't "the same" according to the domain and so Concatenate sees them as different frequencies. I don't want to get 3320 or 2745 features from Interpolate, I want to get 1660. 

In order to get that now, I have to concatenate, then feed one of the original datasets into the reference input of interpolate. I guess it works but feels clunky. 

In any case, I'm still getting some weird behaviour but it seems to be originating in Concatenate actually:

![concat_problem](https://cloud.githubusercontent.com/assets/19228847/25545606/e24c7598-2c1c-11e7-9db0-15a61b9ffe9c.png)

**Comment by markotoplak** [comment]
Hm, this Concatenate plot is very strange - in the worst case it should just show two black curves. Can you perhaps attach these two spectra? I was not able to reproduce this.

**Comment by stuart-cls** [comment]
Closing this as we have Interpolate now and if any other outstanding issues still exist they can be new bugs.
