### ISSUE TITLE
Average Spectra: group by variable

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#231]
See #219 for context. 

@lsammut, I'm planning on working on this unless you still want to?

**Comment by lsammut** [comment]
> See #219 for context.
> 
> @lsammut, I'm planning on working on this unless you still want to?

Hi @stuart-cls, I'm happy for you continue working on this. Unfortunately I'm not sure how much time I'll be able to contribute towards it in the next few months.
