### ISSUE TITLE
OWFFT: zero-filling value not consistent between widget and library

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#265]
Basically, `OWFFT.zff` is an _index of a combo box_ (0, 1, 2, 3) where the index is `2**n` of the value that should be sent to IRFFT. Currently this is sent directly as `IRFFT(zff=self.zff)` which is wrong.

@markotoplak The simple fix is to send `IRFFT(zff=2**self.zff)`, which is what I did so far as it requires no settings migration, etc. Alternative is to make `self.zff` equal to the actual zero-filling-factor, which is more logical and consistent but requires settings migration and GUI changes.

What do you recommend?

**Comment by markotoplak** [comment]
I think the simple fix is fine, but we should document it in the widget. I will just add the comment and accept your PR.
