### ISSUE TITLE
Partial Least Squares (PLS) Regression

### ISSUE THREAD

**Issue by theinhtut** [Quasars/orange-spectroscopy#283]
Hi there,
I'm wondering if it is possible to do PLS Regression for Near Infrared spectra data in order to do predictions.

**Comment by realrk69** [comment]
Even I'm looking for this. Anyone working on it?

**Comment by scott-cls** [comment]
Hi realrk69 - It is funny that you have asked this.  I have started working on this with @stuart-cls yesterday.  Please check back here for updates as we make them available.
Cheers @scott-cls

**Comment by scott-cls** [comment]
Hi again - I see this has been picked up in the Orange main: https://github.com/biolab/orange3/issues/4579

Lets continue the discussion there.

**Comment by realrk69** [comment]
Delighted to hear about it. I too am trying to implement this: https://github.com/biolab/orange3/issues/4579

What are the timelines of release you're looking at?

**Comment by realrk69** [comment]
@scott-cls You can see my pull requent on orange core for PLS and let me know what you think. I'll be creating a pull request for the spectral specific custom models here.
