### ISSUE TITLE
Problems with non DC corrected IFG tranformation

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#315]
The Interferogram to Spectrum widget currently expects IFGs of which the DC background have been subtracted. Agilent, maybe other instruments as well, saves the IFGs "as is" and it is a parameter in the processing workflow to remove the DC part of the signal.

Currently, the Interferogram to Spectrum doesn't deal with the high-frequency signal introduced at the 0V -> DC step. It should be very easy to fix by adding a check box in the widget to subtract/or not the DC background. Or we could even simply do it without asking. Thoughts @markotoplak @stuart-cls? 

To demonstrate the effect this is the result of the raw IFG transformation simply feeding "Interferogram to Spectrum" from the "File" widget:
![image](https://user-images.githubusercontent.com/6304794/54193479-7770d580-44ba-11e9-943d-584e93089e7c.png)

And using the File->_**Preprocess Spectra (Baseline correction/Linear)**_->Interferogram to Spectrum workflow:
![image](https://user-images.githubusercontent.com/6304794/54193534-92dbe080-44ba-11e9-8dd6-8aa67c26dbdf.png)

**Comment by stuart-cls** [comment]
Good catch! I guess I should have finished #282 :)

I agree that it is sensible to correct for the DC offset as part of the normal calculation. I think I'd rather avoid any more checkboxes in this widget at this point. 

I'd like to use something slightly more robust than an edge-to-edge linear baseline.

**Comment by stuart-cls** [comment]
Done in #316
