### ISSUE TITLE
OWHyper: Show all variables in "Use feature" selection

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#330]
It would be nice to use the new Filter/List view from SelectColumns in the Use Feature area. Less nice but still better would be to include Attributes in the DomainModel if there are less than say 20.

Currently our workflows are full of `processing widget` -> `SelectColumns-to-put-feature-in-Metas` -> `OWHyper` -> `SelectColumns-to-put-feature-back-in-Attributes`

@markotoplak I started looking at this but it wasn't clear what was the best approach for future compatibility

**Comment by markotoplak** [comment]
Yes, that could be useful. What is your use case, by the way? Why can't you just "integrate" by closest value?

**Comment by stuart-cls** [comment]
Users find the integrate by closest value really un-intuitive. They never discover it themselves and don't like using it when I show it to them. Especially given a list of say 5 (integrated) features, they are really not confident which one they select, since they are not labelled. Even just for myself, I prefer to use the Combo box and always do the SelectColumns trick.
I would say this is pain point #1 for my imaging users right now.

**Comment by stuart-cls** [comment]
Another reason they can't use closest value, is they need the resulting maps to always correspond to the correct feature:
![multimap](https://user-images.githubusercontent.com/19228847/56694042-15071980-66a3-11e9-912c-bd5a1f102f4b.JPG)
where each hyper widget has specific colour limits for the desired map.
