### ISSUE TITLE
Automation of Spectra Integration

### ISSUE THREAD

**Issue by Guillaumes33** [Quasars/orange-spectroscopy#338]
Hello,

I've just started using Quasar for a job with my university. I need to integrate multiple spectra over specific regions. The Integrate Spectra widget is helpful, but I'm not seeing any easy ways to integrate transformed absorbance spectra where zero is important. Does anyone know of a way to automate the process of integration, so that I can supply a list of spectra files (currently .0 files) and a list of regions to integrate and get the results?

**Comment by stuart-cls** [comment]
Hi, thanks for the question. Perhaps I misunderstand you, but I think that this workflow will do what you ask:
![multifile](https://user-images.githubusercontent.com/19228847/57394752-8e166e80-7183-11e9-87cf-9e00336a2a44.png)

**Comment by Guillaumes33** [comment]
I think that will only work if all my spectra are integrated over the full region. Say I want to integrate all my spectra over two regions like 2000cm^-1 to 3000cm^-1 and 4000cm^-1 to 5500cm^-1. Can I set Quasar up so that these specific regions are integrated without needing to actually go into Integrate Spectra every time I have a new set of spectra?

**Comment by stuart-cls** [comment]
Yes, the Integrate Spectra widget remembers and saves the regions and integration type as part of the workflow file.

**Comment by Guillaumes33** [comment]
Okay, thank you. Is there a way to set it so that Integrate Spectra takes the total magnitude of area? I'm testing on a spectrum that has some negative values, and the widget integrates giving area as negative when I'm only interested in finding the total area.

**Comment by markotoplak** [comment]
What do you mean by total magnitude? The absolute value of the integral? Or sum of the areas that are negative and positive for that integral?

Have you considered integrating with a baseline?

**Comment by Guillaumes33** [comment]
I mean the value I'd get if the entire spectrum was positive, essentially. The sum of the areas that are positive and negative without regard for the sign.

**Comment by markotoplak** [comment]
I do not think there is an integration method in Spectroscopy that would do that. @stuart-cls, am I wrong?

Also, I do not think that would give you the same answer as if the entire spectrum was positive.

**Comment by stuart-cls** [comment]
There is no method that takes the absolute of the spectrum and then integrates that.

**Comment by borondics** [comment]
@Guillaumes33 there are two solutions for this I think. 
You can do a baseline correction, which might distort the integral because it might not be a constant or shift the spectrum up with a constant. I think think the first one is better because if you have negative values you might have baseline problems anyway.
