### ISSUE TITLE
Spectral Series Menu Disappears

### ISSUE THREAD

**Issue by Guillaumes33** [Quasars/orange-spectroscopy#344]
Hello,

This possible bug comes up when I'm looking at two different spectra in two different Spectral Series widgets. I'm not entirely sure what caused it, but the menu button for one of the widgets disappears. Exiting the widget doesn't fix it, but closing the workflow does. It seems to happen if I move one of the high/low sliders and then click the other spectrum.
![SpectrumBug](https://user-images.githubusercontent.com/50418145/57943676-34aeed80-78af-11e9-9caa-c3aec6850b15.jpg)

**Comment by borondics** [comment]
Hi Guillaumes33,

Thanks for noticing this, we will look into it!

Ferenc

**Comment by borondics** [comment]
Is this reproducible (on other systems)? @Guillaumes33 if you reset the widgets and do the same does the Menu button still disappear?

**Comment by Guillaumes33** [comment]
@borondics It does still happen if I reset the widgets.

**Comment by markotoplak** [comment]
@Guillaumes33, how did you install Orange/Quasar? If with the miniconda package, could you open the Orange/Quasar command prompt (search in the start menu) and show me what does the "conda list" return? I am interested in anything that is connected with qt.

It you installed with pip, I am interested in "pip freeze" results. Thank you!

**Comment by Guillaumes33** [comment]
![image](https://user-images.githubusercontent.com/50418145/59846834-795cf700-933b-11e9-86f7-ae7273c1d635.png)
![image](https://user-images.githubusercontent.com/50418145/59846863-8679e600-933b-11e9-93c3-fe87f06e9834.png)
![image](https://user-images.githubusercontent.com/50418145/59846872-8da0f400-933b-11e9-8152-54072b36d3c8.png)

**Comment by Guillaumes33** [comment]
@markotoplak I used the 0.3.2 Miniconda installer.

**Comment by Guillaumes33** [comment]
It seems like this issue no longer occurs with the Miniconda 0.5.0 installation.

**Comment by markotoplak** [comment]
@Guillaumes33, thank you. Interesting... We did upgrade our packages from Qt (visual library) 5.6 to 5.9 - maybe that fixed it.

Otherwise, even before, I have never seen it happen on any of my computers.
