### ISSUE TITLE
Unable to reinstall Quasar

### ISSUE THREAD

**Issue by Guillaumes33** [Quasars/orange-spectroscopy#347]
Hello,

I uninstalled Quasar yesterday in an attempt to unify it with my Anaconda distribution, which didn't quite work. Now I'm trying to reinstall it, and keep getting an error. Not sure if this is something you can help with. Here's part of the setup details. I'm using the miniconda installer for Windows 10.

Installing: qt-5.6.2-vc14h6f8c307_12.tar.bz2
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... ERROR conda.core.link:_execute_post_link_actions(658): An error occurred while installing package '<unknown>::qt-5.6.2-vc14h6f8c307_12'.
LinkError: post-link script failed for package <unknown>::qt-5.6.2-vc14h6f8c307_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\Guillaumes\AppData\Local\Quasar0\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

failed
ERROR conda.core.link:_execute(568): An error occurred while installing package '<unknown>::qt-5.6.2-vc14h6f8c307_12'.
LinkError: post-link script failed for package <unknown>::qt-5.6.2-vc14h6f8c307_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\Guillaumes\AppData\Local\Quasar0\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: ...working... done

LinkError: post-link script failed for package <unknown>::qt-5.6.2-vc14h6f8c307_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\Guillaumes\AppData\Local\Quasar0\Scripts\.qt-post-link.bat
==> script messages <==
<None>

"conda" command exited with 1. Cannot continue.

**Comment by stuart-cls** [comment]
Hi, 

This is https://github.com/Quasars/quasar/issues/5 and https://github.com/biolab/orange3/issues/3819

In the meantime, you can install a Quasar conda environment using the instructions on https://quasar.codes/download/ which boil down to:

````
conda config --append channels conda-forge
conda config --append channels https://quasar.codes/conda/
conda create --name quasar-conda quasar
