### ISSUE TITLE
How to set class_vars for a table?

### ISSUE THREAD

**Issue by Guillaumes33** [Quasars/orange-spectroscopy#358]
Hello,

I'm trying to create data tables from scratch, and I can't figure out how to add class variables without using append, which is deprecated. How do I set class_vars to be string values?

**Comment by markotoplak** [comment]
String variables are only allowed in Orange as metas. In class vars you can use nominal (discrete) variables, which can have values from a specified set of strings. You can construct them like this:

```
import Orange
import numpy as np

nominal_class_var = Orange.data.DiscreteVariable("nominal", values=["First", "Second"])
domain = Orange.data.Domain([Orange.data.ContinuousVariable("a")],
                            class_vars=[nominal_class_var])

dataX = [[3], [5], [1], [3], [2]]
dataY = [[0], [0], [0], [1], [1]]
# could 
# dataY = [nominal_class_var.to_val(v) for v in ["First", "First", "First", "Second", "Second"]]

table = Orange.data.Table.from_numpy(domain, X=dataX, Y=dataY)

print(table)
```

What can you see, is that values if discrete variables are indices into a list of allowed values. The code above prints:

```
[[3 | First],
 [5 | First],
 [1 | First],
 [3 | Second],
 [2 | Second]]
```
