### ISSUE TITLE
File readers with header recognition

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#388]
As we grow we are facing a problem: files from different sources have the same extension, but different content. This is a general Orange problem too. I think the main issue will be simple ASCII files because many instruments output that. Binary files will be usually easy to recognize and use a specific reader.

Goal: make better file readers.

Steps: 
- test if file is binary / ascii
- analyze header
- call specific file reader after recognition
- read data

@markotoplak, @stuart-cls, any comments?

**Comment by markotoplak** [comment]
We already had this problem with some of our readers. All the infrastructure needed for what you propose thus already exists. For some readers we already have a "General reader" that chooses the appropriate format.

But sometimes is impossible to distinguish between file types. In such cases, if a reader for the specific file exists, the user can manually select the reader from a drop down menu.

See DataMetaReader in orangecontrib/spectroscopy/data.py

**Comment by borondics** [comment]
Great! :) Thanks. I am implementing the reader based on this.

**Comment by borondics** [comment]
Great! :) Thanks. I am implementing the reader based on this.

**Comment by markotoplak** [comment]
Closing this, because the infrastructure exists. We only need to be careful when we add new readers that share extensions and then write the disambiguation readers.
