### ISSUE TITLE
CurvePlot: no display for spectra with NaNs when Qt >= 5.12.5

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#408]
The latest installer for Quasar (0.7.1) includes a version bump of Qt to 5.12.5. This means we are now triggering https://github.com/pyqtgraph/pyqtgraph/issues/1057 on spectra containing NaNs.

@markotoplak I can take a stab at this but if
    (a) you prefer to do it
 or (b) you have at least a preferred entrance point
I'd be happy for your input. 

Currently I'm thinking of filtering the input data set in CurvePlot.set_data() for NaNs.

**Comment by markotoplak** [comment]
Thanks for this one. I was wondering what was happening to some windows users... It seems that my Qt was just too old to reproduce it.

I think if we subclass PlotCurveItem and reimplement its setData to drop [nan, inf] elements before passing them further then we could get the previous behaviour.

**Comment by stuart-cls** [comment]
Scott first noticed it with some fresh student installs, and now that I've been setting up a new one at home... 

I'll try your suggestion.
