### ISSUE TITLE
Color problems in Hyperspectra

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#422]
I discovered an interesting bug. 

If I construct the following workflow and exclude a class with `Select Rows`,
![image](https://user-images.githubusercontent.com/6304794/80405510-00b3b900-88c3-11ea-9fb7-a1b77f8ecbe8.png)

...then I get the image in `Hypespectra`.

![image](https://user-images.githubusercontent.com/6304794/80405207-9bf85e80-88c2-11ea-8b70-30d7ac741fff.png)

Notice three things:
- The color bar doesn't show anything. 
- On the top, we have blue (C1) and green (C2) colors and on the bottom blue (C1) and red (C2) which are inconsistent.
- The bottom (Spectra) shows three classes.

Wishes:
- Could the colorbar turn off when we use clusters for coloring on the 2D part?
- We need to fix the color handling because this confusing.

**Comment by markotoplak** [comment]
Nice find! These two widgets seemingly compute colors in different ways and these two should be unified.
