### ISSUE TITLE
SVG export low resolution

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#430]
When exporting from Hyperspectra into SVG I get a very low-resolution image for the 2D plot.
This is how it looks in the widget:
![image](https://user-images.githubusercontent.com/6304794/81152476-4424bc00-8f82-11ea-8a74-1b5cba424e54.png)

And this is when I open it in Inkscape:
![image](https://user-images.githubusercontent.com/6304794/81152533-5141ab00-8f82-11ea-9f59-bfe2e565a441.png)

@markotoplak, maybe this is an Orange issue?

**Comment by markotoplak** [comment]
Probably fixed in biolab/orange-widget-base#43. Update your orange-widget-base.

Or, in Inkscape, try changing object properties (right click on heatmap) -> Image Rendering -> optimizeSpeed.
