### ISSUE TITLE
Markdown (.md) or reStructured Text (.rst)?

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#452]
All the documentation is in Markdown (.md). Recently I came across a problem that apparently can't be solved without some fundamental changes, namely that we can't write mathematical formulas that are more compex than just a simple sub/superscript. However, it seems that we could be happily writing complex stuff in reStructured Text (.rst) and Sphinx would transform it into HTML without problems. Here is an article about it https://www.zverovich.net/2016/06/16/rst-vs-markdown.html.

The question is wheter we would like to switch or not? Considering that our documentation could be quite heavy on math I think it would make sense. In reality, if we had to rewrite all the docs, it is not feasible. So, if we simply rename the .md files to .rst would it work? Or just mix the formats and switch to .rst from now on?

Thoughts?

**Comment by markotoplak** [comment]
Widget documentation is in Markdown so that it can be integrated into the Orange homepage. I would try sticking with .md for widgets and then maybe linking to to .rst for a more mathematical description.

**Comment by borondics** [comment]
OK, but I think rst is encoded into HTML too, so can be still included on
websites, no?

**Comment by markotoplak** [comment]
Orange web page is built directly from .md. They are rendered by Hugo as if they were normal hugo subpages. That is the main reason why we mostly went with Markdown.

**Comment by borondics** [comment]
Ah, I forgot this... On the Hugo website it seems that RST can be used in some way. https://gohugo.io/content-management/formats/

Or alternatively we can bridge this somehow? Using MD in the website content and building the docs with Sphinx and then linking the two together somehow?

**Comment by markotoplak** [comment]
Hm, have no idea. Also, my last suggestion about linking would not work well, I think.

I think it is probably easiest to add html that we want there directly to the .md document. Mathjax formulas have to be marked in someway in html; we can just do that directly. The other easier option would be to modify markdown parses for docs to actually handle math. :)

**Comment by stuart-cls** [comment]
https://hiltmon.com/blog/2017/01/28/mathjax-in-markdown/ might be helpful.

**Comment by markotoplak** [comment]
@stuart-cls, thanks the tip. We are keeping markdown. Fixed in #448.
