### ISSUE TITLE
File widget

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#47]
I think it would be very useful if we have a separate file widget for Orange IR that would allow quick views of files (within reasonable time limits after clicking on a file of course, so no quick displaying of megapixel images)...

**Comment by markotoplak** [comment]
Quick previous when choosing the file such that one of the packages has (forgot which one) are out of scope because we are using file dialogs from Qt. These in turn uses system dialogs. We are not going to rewrite these anytime soon.
