### ISSUE TITLE
Hyperspectra: Plot multiple features on map as composite RGB image

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#487]
This is common in the XRF community, and we've had a few requests for it.

**Comment by noahcabanas** [comment]
@stuart-cls If no one is working on this, I am interested in helping. Would you be able to provide an example of what you're looking for or any specifics for it?

**Comment by borondics** [comment]
I think this would be great! I also had some requests recently and ended up doing it by hand, although in python. @noahcabanas, @stuart-cls I have some code to share here. 

First, I tried something interesting (or maybe interesting for me only).

I created a colormap where the color values were constant and the alpha value was the changing parameter.
```
def alpha_cmp(myrgb):
    N = 256

    vals = np.ones((N, 4))
    vals[:,0:3] = myrgb/(N-1)
    vals[:, 3] = np.linspace(0, 1, N)

    return ListedColormap(vals)
```
Using this function one can make any constant color / changing alpha colormap and plot one image over another.
```
myblue = alpha_cmp(np.array([66, 133, 244]))
mygreen = alpha_cmp(np.array([52, 168, 83]))
myred = alpha_cmp(np.array([234, 67, 53]))
```
Using any nxm matrix series, it is easy to create the composite.
```
fig = plt.figure(figsize=(20,20))
plt.imshow(red, cmap=myred, vmin=np.percentile(red, 5), vmax=np.percentile(red, 95))

plt.imshow(blue, cmap=myblue, vmin=np.percentile(blue, 5), vmax=np.percentile(blue, 95))

plt.imshow(green, cmap=mygreen, vmin=np.percentile(green, 5), vmax=np.percentile(green, 95))
plt.axis(False)
plt.show()
```
The result doesn't look extremely good but it would be possible to nicely overlay it with a visible image, I think...

Then, @markotoplak suggested just simply assigning the red/green/blue channels to the RGB channels of an nxmx4 matrix that is the same as the representation of an image for pyplot.imshow(). It works fine, although I didn't try it with a visible overlay (with some set transparency).

The code I used was something like this:
```
im = np.array([red, green, blue]).T
fig = plt.figure(figsize=(10,10))
plt.imshow(im)
plt.axis(False)
plt.show()
```
The benefit here was that the RGB codes turn into actual RGB colors but this is also a drawback as it is not obvious for me what combination of RGB values produce yellow for example.

**Comment by stuart-cls** [comment]
@noahcabanas Thanks for taking this on! @borondics nice extra information, I'm not 100% sure which implementation is currently popular in the XRF world.

One working example from XRF is PyMCA. They create the red / green / blue images directly and then add them together. See [PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py#L463](https://github.com/vasole/pymca/blob/41820f3bb4ec487f8b2918ac3bce1208562e8354/PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py#L463) and [PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py#L556](https://github.com/vasole/pymca/blob/41820f3bb4ec487f8b2918ac3bce1208562e8354/PyMca5/PyMcaGui/pymca/RGBCorrelatorWidget.py#L556)

Since we already have or can implement colormaps for each color, why not try creating the images with our existing machinery and then linearly combining them as in PyMCA?

Sorry if this is not helpful, but I hope it at least points you in the correct direction.

**Comment by noahcabanas** [comment]
@borondics, @stuart-cls thank you both for the information! I think I have an idea of where to start on this.
