### ISSUE TITLE
Merging Values is not working

### ISSUE THREAD

**Issue by dbedolla** [Quasars/orange-spectroscopy#521]
Hi, 

I have installed Quasar 1.0.0 and I am trying to plot two variables as one. Using Edit domain, they appear as (merged), as shown in the snapshot, 
![image](https://user-images.githubusercontent.com/58698691/108342319-f9a3c180-71da-11eb-9347-c332a7ba411c.png)
but when plotting them, it shows them separately. 
![image](https://user-images.githubusercontent.com/58698691/108342492-2b1c8d00-71db-11eb-9494-14aab5965e3c.png)
Any suggestions?

I tried also to separate into different groups so I would be able to continue the analysis, but it is showing me only one type. 

![image](https://user-images.githubusercontent.com/58698691/108348053-98332100-71e1-11eb-94f8-540bff9b03aa.png)

I also did the the Reset Widget Settings. Thanks to all of you for the great work.

**Comment by markotoplak** [comment]
Thanks for the report. Could you please tell us how did you obtain the data set with repeated value names, the one you input to the widget on your first image?

Does merging perhaps work if the names that you would like to merge are different?

**Comment by dbedolla** [comment]
The original dataset is loaded with Multifile,and the original names are sequential with opus filenaming (.1,.2,.3, etc). The original name of each dataset is not exactly the same, one is called *Ctrl_B1 and the other group of spectra *Ctrl_B3. 
Maybe this snapshot makes it clearer.
![image](https://user-images.githubusercontent.com/58698691/108351176-72a81680-71e5-11eb-9004-041e4726557f.png)

I also concantenated them before, and tried to do there the Edit domain.  But didn't work.

**Comment by markotoplak** [comment]
Ah, I see what the problem is. That would be so much easier if Create class actually joined these things together. So what you see is a Create class bug. I should not allow you to do this... And then all the other components are confused because of repeating names.

I think you will be able to avoid the problem if you created classes differently: so that each of them will get a different name, for example, using Ctrl1, B1; Ctrl2; B2; and so on. Then, try to merge them. Please confirm if it then works.

**Comment by dbedolla** [comment]
Yes Marko, it worked. Thanks a lot! 👍 :-)

**Comment by markotoplak** [comment]
Thank you for your report. You highlighted a valid and useful use case. The next version of Orange/Quasar will support your original usage without any need for additional value merging.

**Comment by markotoplak** [comment]
@dbedolla, the new version of Orange/Quasar, where classes could repeat in Create Class (and your workflow would be much simpler) was released last week. Thanks again!
