### ISSUE TITLE
Integrate output target variables

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#525]
Sparked by the discussion on #524 I realized that there could be a nice improvement to the `Integrate` widget, namely to be able to output the integrals as target variables for using them in regression models. 

Currently this can be done by adding a `Select Columns` widget for example but we could make it more elegant.

**Comment by markotoplak** [comment]
I think you should never really do this. This is a prime example of overfitting. Any linear model should be able to fit this perfectly. 

It would only make sense if we removed the integrated portion (+ some neighborhood) of the spectra, which needs a further downstream operation. So an option would (1) complicate the interface, (2) nudge to something conceptually wrong.

As you say, you can already do it, but I vote it useless enough that we would not want it to be (that) easily available.
