### ISSUE TITLE
Add OPUSReader tests and testfiles

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#53]
Marko:

> Could you also, in a separate pull request, add some tests that read OPUS files and get some values out of then? It would be nice to have a file for each reader variant. The files should be as small as possible, perhaps spanning only a few wavelengths or points with images. If they are small, they can be added into datasets folder directly, if not, we could test them as in TestNea.

I will do this in May.

**Comment by markotoplak** [comment]
This was done.
