### ISSUE TITLE
Ambiguous load file format extension

### ISSUE THREAD

**Issue by ctroein** [Quasars/orange-spectroscopy#535]
Hiya,
I've been implementing a loader for STXM / NEXAFS files in the .hdr/.xim format, based on a couple of examples files from MAX-IV. I found some older mentions of the format on Google, but nothing with details, and I don't know how common this format might be. Anway, I ran into an issue: there is already a loader for files with the .hdr extension, and only one of the loaders will actually be tried if I define this one as also taking .hdr. Maybe a generic solution would be useful in case there are more collisions like this in the future, or maybe something specific could be done in this case to chain the loaders together?

(The format has one file.hdr with metadata and a large number of file_a000,xim, file_a001.xim etc, each with a with plain text matrix, so as a workaround I ended up using *_a000.xim as the file the user will select - which means that the .hdr will also be selectable but won't work.)

**Comment by borondics** [comment]
Hi @ctroein,

Thanks for working on this file loader!

We have similar issues with several instruments and what we ended up doing was to implement a meta-reader class to try all available readers for that extension and then pick the right loader.

Check it out in the case of *.dat files for example here:
https://github.com/Quasars/orange-spectroscopy/blob/5b4372e1b10d715f3c66d64d1590e2bbe8061bb3/orangecontrib/spectroscopy/data.py#L1128

I guess your solution is also OK as long as the data will always have the _*_a000.xim_ file present. You could also pick just the *.xim extension and then either __a**nnn**_ can be selected.

**Comment by ctroein** [comment]
Excellent! I have taken the meta-reader route and added a test case. Pull request coming up. I feel like an old person learning to use a VCR, except it's git. :-D
