### ISSUE TITLE
Obsolete code?

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#536]
I was poking around in the code and found this: 
https://github.com/Quasars/orange-spectroscopy/blob/5b4372e1b10d715f3c66d64d1590e2bbe8061bb3/orangecontrib/spectroscopy/tests/test_owmultifile.py#L159

Is this safe to remove? We could hunt these down as Orange is already at version 3.29...

**Comment by markotoplak** [comment]
Yes, we should remove things like this. Whenever I see them, I remove if the Orange we support is newer than these. If we remove too much, the tests will complain anyway (they run on different versions, among others, the oldest supported one).
