### ISSUE TITLE
Averaging Spectra

### ISSUE THREAD

**Issue by bluewin4** [Quasars/orange-spectroscopy#553]
When I am averaging spectra it generates a single output without any information, that I can find, on the statistics related to that averaging. Without this, it is difficult to do my error analysis later on in my write-up. Is there a way to access the statistics information related to this?

**Comment by borondics** [comment]
What type on info would you like to have?

**Comment by levandoskije** [comment]
> When I am averaging spectra it generates a single output without any information, that I can find, on the statistics related to that averaging. Without this, it is difficult to do my error analysis later on in my write-up. Is there a way to access the statistics information related to this?

You can try to use "SNR" widget, it is possible to see SNR, STD and average.
(There is a preview of the documentation here #554 )

**Comment by bluewin4** [comment]
Thank you!
