### ISSUE TITLE
Peakfitting issues with area calculation

### ISSUE THREAD

**Issue by bluewin4** [Quasars/orange-spectroscopy#556]
So I'm having a problem and I don't know what to do, I'm doing my peak fitting and pulling the areas for each of my underlying peaks and then dividing it by the integrated area of the fitted peak. The results I'm getting don't make sense though, as it only accounts for ~63% of the total peak area.

Does anyone have any idea what's going on? Is this an error or am I missing something?
![image](https://user-images.githubusercontent.com/47462814/118855166-7eb67980-b8a3-11eb-9cc1-88f1055066be.png)

**Comment by stuart-cls** [comment]
@bluewin4 Thanks for your report. 

I wasn't able to reproduce your problem. I created a 6 Voigt peak model and fit the amide I/II region of a representative spectrum (not a good fit but just to test the area calculation).

Area under the total fit: 26.520163313977044
Sum of 6 peak areas: 26.52016331397704

Fits:
![fit](https://user-images.githubusercontent.com/19228847/119194330-249eeb00-ba40-11eb-89fb-6a4fa1392741.png)
Workflow:
![canvas](https://user-images.githubusercontent.com/19228847/119194333-25378180-ba40-11eb-9c55-8f0a2b55da1e.png)
 * In Select Columns I kept only the area Features
 * In Fit -> Python Script, I used:
````
from scipy import integrate

fit = in_data.X[0]
print(fit.shape)
area = integrate.trapz(fit)
print(area)
````
* In Fit Parameters -> -> Python Script:
````
fit = in_data.X[0]
print(fit.shape)
area = fit.sum()
print(area)
````

Please let me know if this helps. If you're still having the problem, we can try exchanging an example / representitive workflow.

Thanks again for your thorough testing and reports, it's really invaluable. I see your pain now with many Voigt peak models, I'll try to work on improving the responsiveness!

**Comment by bluewin4** [comment]
Ah, thanks for the python script. I was just using the integrate spectra widget, it seems that it calculates differently for some reason. Using your code I was able to get it perfect. :)

**Comment by stuart-cls** [comment]
I see now this is a bug. (Well, two bugs). Integrate widget output is correct. 

The `scipy.integrate.trapz()` function being used in the peakfit has no x input, so the areas calculated don't include the x values or spacing.

The correct calculation would be:
````
from scipy import integrate
from orangecontrib.spectroscopy.data import getx

fit = in_data.X[0]
print(fit.shape)
area = integrate.trapz(fit)
print(area)

x = getx(in_data)
a2 = integrate.trapz(fit, x[::-1])
print(a2)
````
where x[::-1] shows the second bug, we are sensitive to the x ordering.

For your case, if all you care about is the normalized area, you can continue to use the code as is and the previous script result to calculate relative areas. If you want an absolute area that relates to the x-axis, you will have to wait until I fix this bug.
