### ISSUE TITLE
Preprocess spectra lags whole workbook after update

### ISSUE THREAD

**Issue by bluewin4** [Quasars/orange-spectroscopy#584]
I updated Orange and now when I have my preproces widgets that worked fine before, even without any data connected, it causes Orange to become pretty much unusably laggy. I had to delete widget by widget too figure out what was causing the lag.
[30gl_analysis_for_matlab.zip](https://github.com/Quasars/orange-spectroscopy/files/7317848/30gl_analysis_for_matlab.zip)
.

**Comment by markotoplak** [comment]
Thanks. This looks like biolab/orange-widget-base#175.

Does it help if you revert to the previous version of widget-base? `orange-widget-base==4.14.0` should not have the bug (and future 4.14.2 won't either).
