### ISSUE TITLE
Getting error with hyperspectra widget

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#61]
The Hyperspectra widget disappeared from my Orange installation.

If I try to run the test from PyCharm I get this:

> .../owhyper.py
> Traceback (most recent call last):
>   File ".../owhyper.py", line 14, in <module>
>     from AnyQt.QtTest import QTest
>   File ".../anaconda3/lib/python3.5/site-packages/AnyQt/QtTest.py", line 4, in <module>
>     from PyQt5.QtTest import *
> ImportError: No module named 'PyQt5.QtTest'
> 
> Process finished with exit code 1

Any ideas?

**Comment by markotoplak** [comment]
Hm, some strange qt stuff. You can try to remove this line and a line
actuall6 using this temporarily. I do not know what happend to your qt
installation. Try to update anyqt - perhaps it will help.
