### ISSUE TITLE
Peak Fit freeze and crash

### ISSUE THREAD

**Issue by fcapitani** [Quasars/orange-spectroscopy#612]
Hello,

I fit a spectrum with the Peak Fit widget successfully, then I added another spectrum to the workflow and the peak fit stopped working. After that, every time I re-run the workflow, no matter the spectrum used, it stops at the Peak fit, it gives the error shown in the attached image, it freezes and I have to force Quasar to shutdown trough the Windows task manager.
Sometimes it freezes without giving any error pop-up.

The fit has 4 peaks, two Lorentzians and two Gaussians. Before fitting, data are cut and baseline corrected through the Preprocess spectra widget. Data are .SPA files loaded with Multifile.
Quasar version is 1.4.0.

Thank you,
Francesco

<img width="574" alt="quasar_fit_error1" src="https://user-images.githubusercontent.com/104839901/166458071-3777343c-448e-42b5-92de-070c70084c93.PNG">

**Comment by fcapitani** [comment]
A couple of additional details, sometimes I get this error too 

<img width="310" alt="quasar_fit_error2" src="https://user-images.githubusercontent.com/104839901/166463982-36a07d2c-8644-4ef4-83ff-fd3df40b4ede.PNG">
 
and the Quasar crash messes up the Windows GUI.

**Comment by markotoplak** [comment]
@fcapitani, does this happen only with the specific peak settings or with whatever peaks you select?

Also, what is the size of your data? How much time did peak fitting require when the fitting completed successfully (the first time you mentioned)?

**Comment by fcapitani** [comment]
Hi @markotoplak,

nice to talk with you ! hope you are fine !
Is is just one SPA spectrum, so 200-300 Kb. The first time it was just a matter of 1 minute max I would say.
I have to say that even when it worked I got that pythonw.exe memory error, but then the workflow didn't stop.
I am trying with a different spectrum, one peak is fine, two peaks, it keeps spinning forever even though the fit preview looks fine 

![image](https://user-images.githubusercontent.com/104839901/166474902-5a59bdac-0bd9-4bda-a708-d5349e8a2eff.png)

![image](https://user-images.githubusercontent.com/104839901/166475020-983c1ca3-c21f-45e2-b65f-5f34b9c040dd.png)

**Comment by fcapitani** [comment]
I don't know if this can help but I can fit my data with the code below without problems.
Before running the code, spectra have been preprocessed using Quasar, exactly the same way as when fitting with Quasar too.

```

  import numpy as np
  from lmfit import Parameters, minimize, models
  import matplotlib.pyplot as plt
  
  filename="C:\\Users\\capitani\\Desktop\\test_fit_T200\\preprocessed_T200.dat"
   
  data=np.loadtxt(filename)
  datatrans=data.transpose()
  x = datatrans[0, :]
  
  for y in datatrans[1:,]:
  
      g1 = models.GaussianModel(prefix='G1_')
      
      pars=g1.make_params()
      pars.update(g1.guess(y, x=x))
      pars['G1_center'].set(320, min=310, max=350)
      pars['G1_sigma'].set(10, min=3)
      
      
      pv1 = models.PseudoVoigtModel(prefix='PV1_')
      
      pars.update(pv1.make_params())
      pars.update(pv1.guess(y, x=x))
      pars['PV1_center'].set(380, min=360, max=400)
      pars['PV1_sigma'].set(15, min=3)
      
      pv2 = models.PseudoVoigtModel(prefix='PV2_')
      
      pars.update(pv2.make_params())
      pars.update(pv2.guess(y, x=x))
      pars['PV2_center'].set(580, min=550, max=600 )
      pars['PV2_sigma'].set(15, min=3)
      
      g2 = models.GaussianModel(prefix='G2_')
      
      pars.update(g2.make_params())
      pars.update(g2.guess(y, x=x))
      pars['G2_center'].set(650, min=600, max=700)
      pars['G2_sigma'].set(15, min=3)
      
      mod = g1 + pv1 + pv2+ g2
      out = mod.fit(y, pars, x=x)
      print(out.fit_report(min_correl=0.25))
      
      plt.plot(x, y, 'b')
      #plt.plot(x, out.init_fit, 'g--')
      plt.plot(x, out.best_fit, 'r-')
      plt.show()
```

**Comment by stuart-cls** [comment]
I think there are two issues here:

1. A bug in the exception handling in the pebble/worker thread/OWPeakFit stack
2. Poor initialization of fit parameters

Regarding the second, @fcapitani in your script you are using both the `.guess()` function and setting limits to the parameters of the models. Are you setting the same limits in the models in Peak Fit?

**Comment by fcapitani** [comment]
Hi @stuart-cls, I tried setting the same limits in the models of Peak Fit  in three situations:
1) reused the same workflow I used when I first encountered the problems. It has already the models set up, I have just modified the limits.
Result: Peak Fit spinning forever, Quasar not responding if you try to remove PeakFit or close Quasar
2) new workflow, just File and Peak Fit widget. Set up the models one by one and then commit manually.
Result: Peak Fit managed to fit, quite slow compared to running my python script, and one of spectra was not fitted properly (the last peak).
3) So I try to modify the frequency limits of the last peak of case (2)
Result: as in (1).

In case (1) and (3), if you try to click on the "play" button in the models, or on "commit", while the widget is spinning , then this error is shown

![image](https://user-images.githubusercontent.com/104839901/170685843-7e18ec7b-99cf-4632-ab36-7e8a7e5c44b8.png)

For sure it looks like, it is more problematic when you run the widget/workflow after the 1st time. Is the peakfit widget automatically running the parameter inizialitation when modifying the values in the models ? Or even directly fitting ?

**Comment by stuart-cls** [comment]
@fcapitani Yes, it re-creates the models and parameters each time, but we don't (yet) do anything clever to guess the initial values. The fitting is also automatic in the preview and on parameter change if auto-commit is selected.

I can't reproduce this bug, but maybe it's something about the spectrum you are using. If you are able, can you email me the processed dataset `preprocessed_T200.dat` that causes the crash for you?

**Comment by fcapitani** [comment]
Hi Stuart,

 

Thanks for the investigation.

I do not think it is something about the spectrum since my Quasar is not able to fit anything anymore, I recently tried a single peak in a spectrum and it doesn’t work as well (peak fit widget stuck at 0%).
Anyway I attach the file you asked and the new spectrum I tried (the peais that at 1020 cm-1).

 

Francesco

 

 

De : Stuart Read ***@***.***> 
Envoyé : samedi 28 mai 2022 00:24
À : Quasars/orange-spectroscopy ***@***.***>
Cc : fcapitani ***@***.***>; Mention ***@***.***>
Objet : Re: [Quasars/orange-spectroscopy] Peak Fit freeze and crash (Issue #612)

 

@fcapitani <https://github.com/fcapitani>  Yes, it re-creates the models and parameters each time, but we don't (yet) do anything clever to guess the initial values. The fitting is also automatic in the preview and on parameter change if auto-commit is selected.

I can't reproduce this bug, but maybe it's something about the spectrum you are using. If you are able, can you email me the processed dataset preprocessed_T200.dat that causes the crash for you?

**Comment by stuart-cls** [comment]
I think it's safe to say this was caused by #743 and should now be solved. Sorry it took so long to get to the bottom of it!
