### ISSUE TITLE
spectral 0.23 doesn't support data type complex256 on Windows

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#628]
@stuart-cls, do you have any ideas where the following error came from? I know it is not from this PR, but did perhaps any dependency change?

```
======================================================================
ERROR: test_envi_comparison (test_readers.TestAgilentReader)
----------------------------------------------------------------------
TypeError: data type 'complex256' not understood
```

_Originally posted by @markotoplak in https://github.com/Quasars/orange-spectroscopy/issues/626#issuecomment-1255057523_

Found it, it was due to change in spectral:

https://github.com/spectralpython/spectral/issues/144
https://github.com/spectralpython/spectral/issues/135

I propose pinning to spectral < 0.23 until they fix it.

**Comment by stuart-cls** [comment]
I guess related issue is that the only test for the envi reader is my agilent comparison 😄

**Comment by markotoplak** [comment]
Thanks for the find and so nice that your tests are so inclusive. :)
