### ISSUE TITLE
Preprocess Spectra widget breaks Color widget

### ISSUE THREAD

**Issue by pisarik** [Quasars/orange-spectroscopy#652]
Hi!

It seems that a `Color` widget inserted after `Preprocess Spectra` widget with at least one preprocessing step turns all absorbance values into missing values '?'.

Here is a [minimal_example.zip](https://github.com/Quasars/orange-spectroscopy/files/10220023/minimal_example.zip).
There, the widget `Empty` does not show any spectra. The output of `Mistake here` contains missing values, while the input is correct.

Ubuntu, python 3.8, Orange 3.34.1, Orange-spectroscopy 0.6.8
It seems that the bug is also reproducible on Windows and Mac OS.

**Comment by markotoplak** [comment]
Thanks for a cool minimal example and the report. Can confirm.

**Comment by markotoplak** [comment]
It is even more general. The same things happens without any Spectroscopy widgets. 

If I use the "Normalize" preprocessors the Color widget does not break the data set for the first chosen normalization method, but if I change it to some other I get the same effect. Seems that Color widget breaks on columns with the same name but different recipes. If I switch back to the first method used, the numbers reappear.

![a](https://user-images.githubusercontent.com/552182/207872384-fb4c2509-45c9-46da-b482-17aacd586919.png)

**Comment by markotoplak** [comment]
@pisarik, this is now fixed in Orange master. Thanks again for the report.
