### ISSUE TITLE
Unify Cut preprocessors

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#661]
Currently the Cut preprocessors come in two flavors: "keep" and "remove".
![image](https://user-images.githubusercontent.com/6304794/218104485-130bab04-bfab-45cc-814b-dabc57b4fc64.png)

As the number of preprocessors are growing it would be nice to unify these two.

The new GUI would be the same with "Low limit" and "High limit" and we could add a radio selector at the bottom to select whether to "keep" or "remove" the part between the limits.

Previous workflows need to be able to run, so backwards compatibility is important.

**Comment by markotoplak** [comment]
Fixed in #661
