### ISSUE TITLE
Multifile cannot read two columns ASCII files properly

### ISSUE THREAD

**Issue by fcapitani** [Quasars/orange-spectroscopy#663]
Hi,

Multifile cannot read correctly spectra stored as two-columns (Wavenumber,Absorbance) ASCII files either comma, tab or space separated. It does not recognize the wavenumbers as features names.

Example:
![image](https://user-images.githubusercontent.com/104839901/222523948-f2e21a00-2f50-47aa-989a-dcf6a31ba796.png)

However, this is correctly read when using the File widget with the Spectra ASCII option (automatic detection leads to the same result of Multifile).

Thanks!
Francesco

**Comment by stuart-cls** [comment]
Thanks for the report Francesco, can confirm I see this too for Quasar 1.7. I created an example file based on your screenshot, attached (change extension from txt to dpt)

 I don't yet understand the problem, since the layout appears identical to the test file "peach_juice.dpt"

[test.txt](https://github.com/Quasars/orange-spectroscopy/files/10875102/test.txt)

**Comment by stuart-cls** [comment]
Scratch that, I fat-fingered a comma in my hand-crafted test file. Now it's working. Can you upload a file that fails?

**Comment by fcapitani** [comment]
Thanks Stuart for the quick reply.
Here's a file producing the behaviour:

[NaCl_newcell_lamp_A1p5_240K.csv](https://github.com/Quasars/orange-spectroscopy/files/10880709/NaCl_newcell_lamp_A1p5_240K.csv)

Just to be clear, here's a screenshot, loading that file with Multifile and File:
![image](https://user-images.githubusercontent.com/104839901/222690151-4948a958-bbf6-4a04-8f49-fcdad802b532.png)

**Comment by stuart-cls** [comment]
Thanks for the example file, I see the issue now.

File readers are keyed off the extension of the file, and for `.csv` files the row-wise Orange Table format takes priority over the column-wise Spectra ASCII format.

To force the Spectra ASCII format in the Multifile widget, you need to select that file type in the OS file chooser:
![select-reader](https://user-images.githubusercontent.com/19228847/222760911-577abdc7-ba40-417b-8553-6b507b8de1df.png)

Alternatively, you can change the file extension to `.dpt` or `.xy` which are unique to the Spectra ASCII reader.

Related: #522

**Comment by stuart-cls** [comment]
Glad it's working, it's definitely an area that isn't obvious what the software is doing.
