### ISSUE TITLE
Scatter plot changed after reopening

### ISSUE THREAD

**Issue by ATGM** [Quasars/orange-spectroscopy#675]
[Workflow Quasar.docx](https://github.com/Quasars/orange-spectroscopy/files/11622981/Workflow.Quasar.docx)

Hello,
Many thanks to all contributers of this wonderful orange package. Unfortunately, I have de following issue:

I'm using Quasar (V1.7.0) for the first time. The process of making a workflow is very easy and clear to me. I was able to import my own spectroscopic data, preprocess it and save it in the total workflow. I'm using the PCA widget and it worked fine when I initially created the workflow, but when I reopen the workflow the scatter plot is showing a different figure. The coloring of the classes is gone. Also the classes are not visible anymore in the attributes section, while if I look in the CSV import widget, the classes are still visible in the data table. Reloading the data doesn't have an effect. It only works again after recreating the workflow. Attached the scatter plots before and after saving the workflow. Thanks for any suggestions!

**Comment by markotoplak** [comment]
Thanks for the bug report. As you expect, these results should indeed be the same.

Can you also share the workflow file (.ows) with us, so that we can debug the issue? Or at least a whole-workflow screenshot.

**Comment by markotoplak** [comment]
Closed for inactivity.
