### ISSUE TITLE
Hyperspectra widget: visual creation of classes #wishlist

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#70]
It would be nice to be able to select multiple areas in a hyperspectral map and assign classes to them that can be used for training learning algorithms.

This lines up with the visual interactivity philosophy of Orange and also would be a great feature!

Necessary addition would be a lasso selection tool, because feature distribution is rarely rectangular :)

I imagine something like this:
![image](https://cloud.githubusercontent.com/assets/6304794/26531997/4969b312-43f6-11e7-8223-2ff16eaaec8b.png)

**Comment by stuart-cls** [comment]
+1 for lasso selection tool :)

**Comment by markotoplak** [comment]
Could you try polygon selection? How should we name it? Should it be lasso?

Also, what do you think should happen if a selection line crosses a pixel? Now only pixels that are wholly inside the selection polygon (or square) are included in a selection.

**Comment by markotoplak** [comment]
Done long ago.
