### ISSUE TITLE
HyperSpectra: is there any option to get a digital average spectra 

### ISSUE THREAD

**Issue by dimaria789** [Quasars/orange-spectroscopy#723]
Hi there
in the HyperSpectra there is a too to save a pciture with the spectra, is there  a possibility to see a digital average spectrum from several areas?
Thanks
Cheers
Maria

**Comment by borondics** [comment]
Hi Maria,
Yes, there are many ways of doing it. You can display average spectra in the little window below the image. You can select regions or use clusters from previous clustering. Or you need to send the data to an "Average Spectra" widget. Then you can "Save Data" or view it in "Spectra".

I encourage you to explore the menu items and widgets and try to connect these I was mentioning above. 

I hope this helps.

**Comment by dimaria789** [comment]
Yes, thanks! IT helps!
