### ISSUE TITLE
Hyperspectra: feature request for saving the image

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#73]
CTRL-S or CMD-S currently exports the figure of the "Curves" part of the Hyperspectra widget, but we would need to enable the exporting of the image on the top as well.

**Comment by borondics** [comment]
OK, I started working on this and in surprisingly short time I could copy paste the functionality from the "Curves" widget. Now the picture saves, but it is pretty ugly. I'll work on making it prettier...

**Comment by markotoplak** [comment]
Fixed in master.
