### ISSUE TITLE
Peakfit: Some computers start more processes than available memory (was "crashing on Windows")

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#743]
When the peakfit main pool runs, `cmd.exe` crashes and the processing never completes. The preview calculation works correctly.

![image](https://github.com/user-attachments/assets/d7551763-df9d-493b-9841-bfaa21db3013)

I'll update this issue when I find the reason.

**Comment by stuart-cls** [comment]
This appears to be triggered by Windows computers with many cores and not much RAM, but that could be a misdiagnosis. The multiprocessing pool in peakfit starts 12 (`os.cpu_count()`) processes, and during the process setup there is a `MemoryError`, which leads to `ImportError: DLL load failed while importing _multiarray_umath: The paging file is too small for this operation to complete.` for many many modules

I was going to suggest replacing the default with `psutil.cpu_count(logical=False)` but it turns out on this machine that returns 10 (10 cores, 12 logical cores :shrug: ), which is still too much. Even 6 which works when the machine is freshly rebooted doesn't work with other stuff going on. 

For small datasets starting up the multiprocessing is slow for not much benefit. I'm a bit stumped about how to keep the performance for large cpu/memory machines while not crashing on the simple easy stuff. @markotoplak any thoughts?

**Comment by markotoplak** [comment]
Wow, that seems like a promising line of though. So good that you traced this back to MemoryError!

How much RAM does that particular particular machine have? And how much of it is already spent by Orange when the data is loaded?

I don't have any idea. What I'd try is limit the number of processes to 2 (or even 1) and then enable power users to set a system variable somewhere that puts it higher. The main reason for offloading to separate processes, was, for me, that then it does not just freeze everything.

I'd prefer using threads (no problems with memory usage there), but when I tried, this lmfit used a function internally (from scipy) that did not release the GIL. If perhaps the GIL release now works, the best solution would be to convert this into threads.

Here I am guessing. Or, alternatively, if memory is problematic here, the data to processes should be sent in smaller chunks. Perhaps chunks are too big currently, or worse, the whole data is sent and only then selected.

**Comment by borondics** [comment]
I had reports from users as well that it crashes. 

It seems that lmfit doesn't play nicely on windows. Should we try to replace it with something else?

**Comment by stuart-cls** [comment]
> How much RAM does that particular particular machine have? And how much of it is already spent by Orange when the data is loaded?

It's only 16 GB, most of which is taken up by Windows 11 :) I think the problem surfaced with these new processors, a friend explained that they have 2 "performance cores" with proper hyperthreading (thus the extra 2 logical processors) and then 8 "efficiency" cores, like ARM chips in smart phones I guess. Anyway the traditional assumption that `os.cpu_count()` and memory roughly scale together is completely broken for these.

Just the widget alone (widgetpreview) uses 214 MB, when the preview process starts it goes to 380 MB. With the limit set to 2 processes it increases to 690 MB during fitting. So it seems that each processing running peakfit_calculate module takes ~160 MB. `import orangecontrib.spectroscopy.widgets.peakfit_compute` in a REPL takes ~110 MB so it roughly checks out.

> What I'd try is limit the number of processes to 2 (or even 1) and then enable power users to set a system variable somewhere that puts it higher.

This is where I was leaning too, anything else drops you down a dark hole of edge cases :)

> Perhaps chunks are too big currently, or worse, the whole data is sent and only then selected.

Chunks are single rows, so I don't think it comes from the data. And the crash happens even if you just run the widget on it's own with `python -m orangecontrib.spectroscopy.widgets.owpeakfit` which only loads 3 rows of collagen.csv.

> Should we try to replace it with something else?

I like lmfit, it's commonly used in spectroscopy, and it's deeply integrated into the widget data model. So I'd rather not :)

I will check the threading / GIL and then do a PR with the process limits above.

**Comment by stuart-cls** [comment]
Indeed, the problem with the GIL still occurs (2.7 s to fit all rows of collagen with `multiprocessing.Pool` vs 72 s with `multiprocessing.pool.ThreadPool`). I don't care to investigate it further at this point so let's go with simple override-able limits.
