### ISSUE TITLE
Multifile test crashing on latest Orange

### ISSUE THREAD

**Issue by markotoplak** [Quasars/orange-spectroscopy#746]
On the latest Orange version some Multifiles tests are crashing. This should be investigated before the next release.

**Comment by stuart-cls** [comment]
It's from this commit: https://github.com/biolab/orange-widget-base/commit/511f4be4a5e8d52d0f3852192d49973229bdb56c#diff-88d809289fc4b688675211f4efadb60dc3ef607c252dd9f6d99611ffa3b6f6e3

**Comment by stuart-cls** [comment]
I guess something about the way that `TestOWMultifile.test_spectra_almost_same_wavenumbers` is patching the `SPAReader` and updating the FileFormat cache _after_ widget instantation? The `open_filename_dialog` logic is almost identical with the default value as used in OWMultifile.
