### ISSUE TITLE
Peak fit parallelization

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#766]
Since we have problems with the parallel fitting I was thinking if we could simply use Dask for this?

**Comment by stuart-cls** [comment]
As far as I know, the problem is fixed (#748)! If not, we need a new bug :)

Dask is another good option for parallelization but we don't have dask in our standard release.

**Comment by stuart-cls** [comment]
Two processes by default, but you can override on beefier machines by setting an environment variable:

> By default this is limited to 2 extra processes, but this can be
overridden by setting the environment variable `QUASAR_N_PROCESSES` to the desired number, or `all`
to use the default value returned by `os.cpu_count()`.

I put it in the docs but it's not showing up on https://orange-spectroscopy.readthedocs.io/en/latest/widgets/peakfit.html 🧐

**Comment by stuart-cls** [comment]
Fixed the readthedocs.

**Comment by borondics** [comment]
@stuart-cls, I was just thinking about this environment variable. Would it make more sense to have a setting somewhere in Quasar? Either in the menu or the widget itself?
