### ISSUE TITLE
Testsuite failure: AttributeError: 'TestCommonMixin' object has no attribute 'preprocessors'

### ISSUE THREAD

**Issue by rolandmas** [Quasars/orange-spectroscopy#770]
Hello, your friendly Debian package maintainer here :-)

Automated testing in the Debian CI system reveals a series of failures when running the testsuite on orange-spectroscopy 0.7.2. A large number of tests fail with the same kind of error message, such as "AttributeError: 'TestCommonMixin' object has no attribute 'preprocessors'" (the class name differs, but it's always a SomethingMixin). Since the testsuite is run at package build time, this means the package suffers from a "fails to build from source" bug, which is considered release-critical (see https://bugs.debian.org/1085956) and prevents orange-spectroscopy to migrate to Debian "testing", a first step towards the stable release.

Here's an excerpt of the build log, where I isolated one test:

```
   dh_auto_test -O--buildsystem=pybuild
I: pybuild base:311: cd /build/orange-spectroscopy-0.7.2/.pybuild/cpython3_3.12_orange-spectroscopy/build; python3.12 -m pytest --verbosity=2 -k "TestCommonMixin and test_slightly_different_domain" orangecontrib
/spectroscopy/tests/test_preprocess.py
============================= test session starts ==============================
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0 -- /usr/bin/python3.12
cachedir: .pytest_cache
rootdir: /build/orange-spectroscopy-0.7.2
configfile: pyproject.toml
plugins: xvfb-3.0.0, typeguard-4.4.0, anyio-4.6.0
collecting ... collected 147 items / 146 deselected / 1 selected

orangecontrib/spectroscopy/tests/test_preprocess.py::TestCommonMixin::test_slightly_different_domain FAILED [100%]

=================================== FAILURES ===================================
________________ TestCommonMixin.test_slightly_different_domain ________________

self = <spectroscopy.tests.test_preprocess.TestCommonMixin object at 0x7fea96314470>

    def test_slightly_different_domain(self):
        """ If test data has a slightly different domain then (with interpolation)
        we should obtain a similar classification score. """
        # rows full of unknowns make LogisticRegression undefined
        # we can obtain them, for example, with EMSC, if one of the badspectra
        # is a spectrum from the data
        learner = LogisticRegressionLearner(max_iter=1000, preprocessors=[_RemoveNaNRows()])
    
>       for proc in self.preprocessors:
E       AttributeError: 'TestCommonMixin' object has no attribute 'preprocessors'

orangecontrib/spectroscopy/tests/test_preprocess.py:95: AttributeError
=============================== warnings summary ===============================
../../../../../usr/lib/python3/dist-packages/Orange/evaluation/testing.py:704
  /usr/lib/python3/dist-packages/Orange/evaluation/testing.py:704: PytestCollectionWarning: cannot collect test class 'TestOnTestData' because it has a __init__ constructor (from: .pybuild/cpython3_3.12_orange-spectroscopy/build/orangecontrib/spectroscopy/tests/test_preprocess.py)
    class TestOnTestData(Validation):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED orangecontrib/spectroscopy/tests/test_preprocess.py::TestCommonMixin::test_slightly_different_domain - AttributeError: 'TestCommonMixin' object has no attribute 'preprocessors'
================= 1 failed, 146 deselected, 1 warning in 1.12s =================
E: pybuild pybuild:389: test: plugin pyproject failed with: exit code=1: cd /build/orange-spectroscopy-0.7.2/.pybuild/cpython3_3.12_orange-spectroscopy/build; python3.12 -m pytest --verbosity=2 -k "TestCommonMixin and test_slightly_different_domain" orangecontrib/spectroscopy/tests/test_preprocess.py
dh_auto_test: error: pybuild --test --test-pytest -i python{version} -p 3.12 returned exit code 13
```

Full build log attached, in case there's something I missed; maybe an incorrect dependency?

Any help will be welcome, whether as a patch or as a pointer to what I do wrong on the Debian packaging side.

[orange-spectroscopy_0.7.2-2_amd64.build.log](https://github.com/user-attachments/files/17598389/orange-spectroscopy_0.7.2-2_amd64.build.log)

**Comment by rolandmas** [comment]
Okay, my bad. Further investigation led to the understanding that the *Mixin classes are not meant to be run as testcase themselves. Excluding these classes from the test runs fixes the failure. Apologies for the false alert.

**Comment by markotoplak** [comment]
Thanks for the report though. May I ask why do you run these tests with pytest? For this package we only use unittest - that might explain the incompatibility.

I do not know how free individual package built instructions can be in Debian, but replacing pytest with corresponding `python -m unittest orangecontrib.spectroscopy.tests` or similar would make more sense here.

**Comment by rolandmas** [comment]
Mainly because pytest is very well integrated with pybuild and the Debian Python packaging culture, and also because there's a pytest-xvfb plugin that allows running testsuites for GUI apps even on headless CI servers or isolated chroots.
Also, it's supposed to be compatible with unittest testsuites… apart from this quirk, obviously :-)

**Comment by markotoplak** [comment]
Thanks for the explanation. I'll see it is getting popular and will try testing this package with it too in the future.
